//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Hunde.ProxyEstado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conductaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string est_nutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string actividad {
            get {
                return this.actividadField;
            }
            set {
                if ((object.ReferenceEquals(this.actividadField, value) != true)) {
                    this.actividadField = value;
                    this.RaisePropertyChanged("actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_estado {
            get {
                return this.cod_estadoField;
            }
            set {
                if ((this.cod_estadoField.Equals(value) != true)) {
                    this.cod_estadoField = value;
                    this.RaisePropertyChanged("cod_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conducta {
            get {
                return this.conductaField;
            }
            set {
                if ((object.ReferenceEquals(this.conductaField, value) != true)) {
                    this.conductaField = value;
                    this.RaisePropertyChanged("conducta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string est_nut {
            get {
                return this.est_nutField;
            }
            set {
                if ((object.ReferenceEquals(this.est_nutField, value) != true)) {
                    this.est_nutField = value;
                    this.RaisePropertyChanged("est_nut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEstado.IServicioEstado")]
    public interface IServicioEstado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstado/ListarEstados", ReplyAction="http://tempuri.org/IServicioEstado/ListarEstadosResponse")]
        MVC_Hunde.ProxyEstado.Estado[] ListarEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstado/ListarEstados", ReplyAction="http://tempuri.org/IServicioEstado/ListarEstadosResponse")]
        System.Threading.Tasks.Task<MVC_Hunde.ProxyEstado.Estado[]> ListarEstadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEstadoChannel : MVC_Hunde.ProxyEstado.IServicioEstado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEstadoClient : System.ServiceModel.ClientBase<MVC_Hunde.ProxyEstado.IServicioEstado>, MVC_Hunde.ProxyEstado.IServicioEstado {
        
        public ServicioEstadoClient() {
        }
        
        public ServicioEstadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEstadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Hunde.ProxyEstado.Estado[] ListarEstados() {
            return base.Channel.ListarEstados();
        }
        
        public System.Threading.Tasks.Task<MVC_Hunde.ProxyEstado.Estado[]> ListarEstadosAsync() {
            return base.Channel.ListarEstadosAsync();
        }
    }
}
