//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Hunde.ProxyTratamiento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tratamiento", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Tratamiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_tratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_tratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_tratField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_trat {
            get {
                return this.cod_tratField;
            }
            set {
                if ((this.cod_tratField.Equals(value) != true)) {
                    this.cod_tratField = value;
                    this.RaisePropertyChanged("cod_trat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_trat {
            get {
                return this.est_tratField;
            }
            set {
                if ((this.est_tratField.Equals(value) != true)) {
                    this.est_tratField = value;
                    this.RaisePropertyChanged("est_trat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_trat {
            get {
                return this.nom_tratField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_tratField, value) != true)) {
                    this.nom_tratField = value;
                    this.RaisePropertyChanged("nom_trat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyTratamiento.IServicioTratamiento")]
    public interface IServicioTratamiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTratamiento/listarTratamientos", ReplyAction="http://tempuri.org/IServicioTratamiento/listarTratamientosResponse")]
        MVC_Hunde.ProxyTratamiento.Tratamiento[] listarTratamientos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTratamiento/listarTratamientos", ReplyAction="http://tempuri.org/IServicioTratamiento/listarTratamientosResponse")]
        System.Threading.Tasks.Task<MVC_Hunde.ProxyTratamiento.Tratamiento[]> listarTratamientosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioTratamientoChannel : MVC_Hunde.ProxyTratamiento.IServicioTratamiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTratamientoClient : System.ServiceModel.ClientBase<MVC_Hunde.ProxyTratamiento.IServicioTratamiento>, MVC_Hunde.ProxyTratamiento.IServicioTratamiento {
        
        public ServicioTratamientoClient() {
        }
        
        public ServicioTratamientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTratamientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTratamientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTratamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Hunde.ProxyTratamiento.Tratamiento[] listarTratamientos() {
            return base.Channel.listarTratamientos();
        }
        
        public System.Threading.Tasks.Task<MVC_Hunde.ProxyTratamiento.Tratamiento[]> listarTratamientosAsync() {
            return base.Channel.listarTratamientosAsync();
        }
    }
}
